include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AmberSettings
AmberSettings_INSTALL_PATH = /Library/PreferenceBundles
AmberSettings_FILES = AmberSettings.m
AmberSettings_LDFLAGS = -undefined dynamic_lookup

include $(THEOS_MAKE_PATH)/bundle.mk
