include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = AmberSettings
AmberSettings_INSTALL_PATH = /Library/PreferenceBundles
AmberSettings_FILES = AmberSettings.m
AmberSettings_FRAMEWORKS = Preferences
AmberSettings_PRIMARY_FRAMEWORK = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk
