#import <Preferences/PSListController.h>
#import <Preferences/PSSpecifier.h>
#import <Preferences/PSTableCell.h>
#import "../SCPaths.h"
#import <UIKit/UIKit.h>

@interface SCRootListController : PSListController @end
static void SCPreferencesStateChanged(CFNotificationCenterRef c,void *o,CFStringRef n,const void *obj,CFDictionaryRef u){SCRootListController *vc=(__bridge id)o;dispatch_async(dispatch_get_main_queue(),^{[vc reloadSpecifierID:@"ButtonHookStatus"];[vc reloadSpecifierID:@"LastActionDate"];[vc reloadSpecifierID:@"LastActionStatus"];});}
@implementation SCRootListController
- (instancetype)init{if((self=[super init])){CFNotificationCenterRef dc=CFNotificationCenterGetDarwinNotifyCenter();CFNotificationCenterAddObserver(dc,(__bridge const void*)self,SCPreferencesStateChanged,CFSTR("com.spark.SneakyCam.actionstatechanged"),NULL,CFNotificationSuspensionBehaviorDeliverImmediately);CFNotificationCenterAddObserver(dc,(__bridge const void*)self,SCPreferencesStateChanged,CFSTR("com.spark.SneakyCam.recordingstatechanged"),NULL,CFNotificationSuspensionBehaviorDeliverImmediately);}return self;}
- (PSSpecifier *)item:(NSString *)name key:(NSString *)key def:(id)def cell:(PSCellType)cell{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:@selector(setPreferenceValue:specifier:) get:@selector(readPreferenceValue:) detail:Nil cell:cell edit:Nil];[s setProperty:key forKey:@"key"];[s setProperty:key forKey:@"id"];[s setProperty:def forKey:@"default"];[s setProperty:@"com.spark.SneakyCam" forKey:@"defaults"];return s;}
- (PSSpecifier *)choice:(NSString *)name key:(NSString *)key def:(id)def titles:(NSArray *)titles values:(NSArray *)values{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:@selector(setPreferenceValue:specifier:) get:@selector(readPreferenceValue:) detail:NSClassFromString(@"PSListItemsController") cell:PSLinkListCell edit:Nil];[s setProperty:key forKey:@"key"];[s setProperty:key forKey:@"id"];[s setProperty:def forKey:@"default"];[s setProperty:@"com.spark.SneakyCam" forKey:@"defaults"];[s setProperty:titles forKey:@"validTitles"];[s setProperty:values forKey:@"validValues"];[s setProperty:titles forKey:@"titles"];[s setProperty:values forKey:@"values"];return s;}
- (PSSpecifier *)button:(NSString *)name action:(SEL)action{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:Nil cell:PSButtonCell edit:Nil];s.buttonAction=action;return s;}
- (NSArray *)specifiers{if(_specifiers)return _specifiers;NSMutableArray *a=[NSMutableArray array];PSSpecifier *main=[PSSpecifier groupSpecifierWithName:@"SneakyCam 隐私相机"];[main setProperty:@"iOS 15–17 · Dopamine Rootless / RootHide" forKey:@"footerText"];[a addObject:main];
[a addObject:[self item:@"功能总开关" key:@"Enabled" def:@NO cell:PSSwitchCell]];[a addObject:[self item:@"允许拍照片" key:@"PhotoEnabled" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"拍照静音" key:@"PhotoSilent" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"允许拍视频" key:@"VideoEnabled" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"录像绿色指示点" key:@"RecordingIndicator" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"锁屏保持录制" key:@"LockScreenKeepRecording" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"保存到 /var/mobile/Media/Camera" key:@"SaveToRoot" def:@NO cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"相机"]];[a addObject:[self choice:@"选择摄像头" key:@"CameraDevice" def:@"AVCaptureDevicePositionBack" titles:@[@"后置摄像头",@"前置摄像头"] values:@[@"AVCaptureDevicePositionBack",@"AVCaptureDevicePositionFront"]]];[a addObject:[self choice:@"视频质量" key:@"VideoQuality" def:@"AVCaptureSessionPreset1920x1080" titles:@[@"288p",@"720p",@"1080p",@"2160p"] values:@[@"AVCaptureSessionPreset352x288",@"AVCaptureSessionPreset1280x720",@"AVCaptureSessionPreset1920x1080",@"AVCaptureSessionPreset3840x2160"]]];[a addObject:[self choice:@"视频帧率" key:@"FrameRate" def:@"60" titles:@[@"30 帧",@"60 帧",@"120 帧（非 4K）",@"240 帧（非 4K）"] values:@[@"30",@"60",@"120",@"240"]]];[a addObject:[self item:@"播放音视频时禁用" key:@"DisableIfPlayback" def:@NO cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"音量键"]];[a addObject:[self item:@"使用音量键" key:@"UseVolumeButtons" def:@YES cell:PSSwitchCell]];[a addObject:[self choice:@"音量减动作" key:@"VolumeDownAction" def:@"photo" titles:@[@"拍照",@"录像",@"关闭"] values:@[@"photo",@"video",@"off"]]];[a addObject:[self choice:@"音量加动作" key:@"VolumeUpAction" def:@"video" titles:@[@"拍照",@"录像",@"关闭"] values:@[@"photo",@"video",@"off"]]];[a addObject:[self item:@"震动反馈" key:@"HapticFeedback" def:@YES cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"最近操作"]];[a addObject:[self item:@"按键兼容状态" key:@"ButtonHookStatus" def:@"等待 SpringBoard 加载" cell:PSTitleValueCell]];[a addObject:[self item:@"时间" key:@"LastActionDate" def:@"尚无操作" cell:PSTitleValueCell]];[a addObject:[self item:@"状态" key:@"LastActionStatus" def:@"等待按键或控制中心操作" cell:PSTitleValueCell]];[a addObject:[self button:@"打开 Camera 文件夹" action:@selector(openCamera)]];PSSpecifier *footer=[PSSpecifier emptyGroupSpecifier];[footer setProperty:@"双击音量加开始/停止录像；双击音量减拍照。\n@Huayuarc Fix" forKey:@"footerText"];[a addObject:footer];_specifiers=a;return _specifiers;}
- (id)readPreferenceValue:(PSSpecifier *)s{return SCReadPreferences()[s.properties[@"key"]]?:s.properties[@"default"];}
- (void)setPreferenceValue:(id)v specifier:(PSSpecifier *)s{NSString *key=s.properties[@"key"];SCWritePreference(key,v);CFNotificationCenterRef dc=CFNotificationCenterGetDarwinNotifyCenter();CFNotificationCenterPostNotification(dc,CFSTR("com.spark.SneakyCam"),NULL,NULL,YES);if([key isEqualToString:@"Enabled"]||[key isEqualToString:@"RecordingIndicator"])CFNotificationCenterPostNotification(dc,CFSTR("com.spark.SneakyCam.enabledchanged"),NULL,NULL,YES);}
- (void)openCamera{NSString *dir=@"/var/mobile/Media/Camera",*anchor=[dir stringByAppendingPathComponent:@".SneakyCam-OpenHere"];NSFileManager *fm=NSFileManager.defaultManager;[fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];if(![fm fileExistsAtPath:anchor])[@"SneakyCam folder anchor" writeToFile:anchor atomically:YES encoding:NSUTF8StringEncoding error:nil];NSURL *url=[NSURL URLWithString:@"filza://view/var/mobile/Media/Camera/.SneakyCam-OpenHere"];if([UIApplication.sharedApplication canOpenURL:url])[UIApplication.sharedApplication openURL:url options:@{} completionHandler:nil];else{SCWritePreference(@"LastActionStatus",@"未检测到 Filza，请安装后重试");[self reloadSpecifierID:@"LastActionStatus"];}}
- (void)dealloc{CFNotificationCenterRemoveObserver(CFNotificationCenterGetDarwinNotifyCenter(),(__bridge const void*)self,NULL,NULL);}
@end
