#import "SAAPIStore.h"
@implementation SAAPIStore { NSArray *_apis; NSMutableSet *_favorites; }
+ (instancetype)shared { static id s; static dispatch_once_t once; dispatch_once(&once, ^{ s=[self new]; }); return s; }
- (instancetype)init { if((self=[super init])) { NSString *p=[[NSBundle bundleForClass:self.class] pathForResource:@"api" ofType:@"json"]; NSData *d=[NSData dataWithContentsOfFile:p]; id o=d?[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]:nil; _apis=[o isKindOfClass:NSArray.class]?o:@[]; NSArray *f=[[NSUserDefaults standardUserDefaults] arrayForKey:@"SAFavorites"]?:@[]; _favorites=[NSMutableSet setWithArray:f]; } return self; }
- (NSArray *)apis{return _apis;}
- (NSString *)key:(NSDictionary *)a { return [NSString stringWithFormat:@"%@|%@",a[@"method"]?:@"GET",a[@"url"]?:@""]; }
- (BOOL)isFavorite:(NSDictionary *)a{return [_favorites containsObject:[self key:a]];}
- (void)toggleFavorite:(NSDictionary *)a { NSString*k=[self key:a]; if([_favorites containsObject:k])[_favorites removeObject:k];else[_favorites addObject:k]; [[NSUserDefaults standardUserDefaults] setObject:_favorites.allObjects forKey:@"SAFavorites"]; }
- (NSArray *)filtered:(NSString *)q method:(NSString *)m favoritesOnly:(BOOL)f { NSMutableArray*r=[NSMutableArray array]; NSString*needle=q.lowercaseString?:@""; for(NSDictionary*a in _apis){if(f&&![self isFavorite:a])continue;if(m.length&&![a[@"method"] isEqual:m])continue;NSString*u=[a[@"url"]?:@"" lowercaseString];if(needle.length&&[u rangeOfString:needle].location==NSNotFound)continue;[r addObject:a];}return r;}
- (NSArray *)risksForAPI:(NSDictionary *)a { NSMutableArray*r=[NSMutableArray array];NSString*u=a[@"url"]?:@"";NSString*all=[NSString stringWithFormat:@"%@ %@",u,a];if([u hasPrefix:@"http://"])[r addObject:@"明文 HTTP"];if([all rangeOfString:@"token" options:NSCaseInsensitiveSearch].location!=NSNotFound)[r addObject:@"硬编码 Token"];if([all rangeOfString:@"sign" options:NSCaseInsensitiveSearch].location!=NSNotFound)[r addObject:@"硬编码签名"];if([u rangeOfString:@"[phone]"].location==NSNotFound&&[a.description rangeOfString:@"[phone]"].location==NSNotFound)[r addObject:@"缺少手机号占位符"];if([u rangeOfString:@"[object%20HTMLInputElement]"].location!=NSNotFound)[r addObject:@"异常模板值"];return r;}
- (NSDictionary *)statistics { NSUInteger post=0,http=0,risky=0;NSMutableSet*d=[NSMutableSet set];for(NSDictionary*a in _apis){if([a[@"method"] isEqual:@"POST"])post++;NSURL*u=[NSURL URLWithString:a[@"url"]];if(u.host)[d addObject:u.host];if([a[@"url"] hasPrefix:@"http://"])http++;if([self risksForAPI:a].count)risky++;}return @{ @"total":@(_apis.count),@"post":@(post),@"get":@(_apis.count-post),@"domains":@(d.count),@"http":@(http),@"risky":@(risky),@"favorites":@(_favorites.count)};}
- (NSString *)previewForAPI:(NSDictionary *)a phone:(NSString *)phone { NSString*(^rep)(NSString*)=^NSString*(NSString*s){return [s stringByReplacingOccurrencesOfString:@"[phone]" withString:phone.length?phone:@"138****0000"];};NSMutableDictionary*x=[NSMutableDictionary dictionaryWithDictionary:a];x[@"url"]=rep(a[@"url"]?:@"");NSMutableDictionary*data=[NSMutableDictionary dictionary];[a[@"data"] enumerateKeysAndObjectsUsingBlock:^(id k,id v,BOOL*stop){data[k]=[v isKindOfClass:NSString.class]?rep(v):v;}];x[@"data"]=data;NSData*j=[NSJSONSerialization dataWithJSONObject:x options:NSJSONWritingPrettyPrinted error:nil];return [[NSString alloc]initWithData:j encoding:NSUTF8StringEncoding];}
- (NSString *)exportReport { NSDictionary*s=[self statistics];return [NSString stringWithFormat:@"API 接口审计报告\n总计：%@\nPOST：%@  GET：%@\n域名：%@\n明文 HTTP：%@\n风险项：%@\n收藏：%@",s[@"total"],s[@"post"],s[@"get"],s[@"domains"],s[@"http"],s[@"risky"],s[@"favorites"]]; }
@end
