#import "SAAPIListController.h"
#import "SAAPIStore.h"
@interface SAAPIListController()<UISearchBarDelegate>@property NSArray*items;@property UISearchController*search;@end
@implementation SAAPIListController
- (void)viewDidLoad{[super viewDidLoad];self.title=self.favoritesOnly?@"收藏接口":self.methodFilter.length?[self.methodFilter stringByAppendingString:@" 接口"]:@"全部接口";self.tableView.rowHeight=70;self.search=[[UISearchController alloc]initWithSearchResultsController:nil];self.search.searchResultsUpdater=self;self.search.obscuresBackgroundDuringPresentation=NO;self.search.searchBar.placeholder=@"搜索域名、URL 或路径";self.navigationItem.searchController=self.search;self.definesPresentationContext=YES;[self reload];}
- (void)reload{self.items=[[SAAPIStore shared] filtered:self.search.searchBar.text method:self.methodFilter favoritesOnly:self.favoritesOnly];self.navigationItem.prompt=[NSString stringWithFormat:@"%lu 个匹配项",(unsigned long)self.items.count];[self.tableView reloadData];}
- (void)updateSearchResultsForSearchController:(UISearchController*)s{[self reload];}
- (NSInteger)tableView:(UITableView*)t numberOfRowsInSection:(NSInteger)s{return self.items.count;}
- (UITableViewCell*)tableView:(UITableView*)t cellForRowAtIndexPath:(NSIndexPath*)i{UITableViewCell*c=[t dequeueReusableCellWithIdentifier:@"a"];if(!c)c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:@"a"];NSDictionary*a=self.items[i.row];NSURL*u=[NSURL URLWithString:a[@"url"]];c.textLabel.text=u.host?:a[@"url"];c.detailTextLabel.text=[NSString stringWithFormat:@"%@  %@",a[@"method"],u.path.length?u.path:a[@"url"]];c.detailTextLabel.numberOfLines=2;c.accessoryType=[[SAAPIStore shared]isFavorite:a]?UITableViewCellAccessoryCheckmark:UITableViewCellAccessoryDisclosureIndicator;c.textLabel.textColor=[a[@"method"]isEqual:@"POST"]?UIColor.systemOrangeColor:UIColor.labelColor;return c;}
- (void)tableView:(UITableView*)t didSelectRowAtIndexPath:(NSIndexPath*)i{[t deselectRowAtIndexPath:i animated:YES];NSDictionary*a=self.items[i.row];NSArray*r=[[SAAPIStore shared]risksForAPI:a];NSString*m=[NSString stringWithFormat:@"方法：%@\n风险：%@\n\n%@",a[@"method"],r.count?[r componentsJoinedByString:@"、"]:@"未发现",[[SAAPIStore shared]previewForAPI:a phone:nil]];UIAlertController*x=[UIAlertController alertControllerWithTitle:@"本地请求预览" message:m preferredStyle:UIAlertControllerStyleAlert];[x addAction:[UIAlertAction actionWithTitle:[[SAAPIStore shared]isFavorite:a]?@"取消收藏":@"收藏" style:UIAlertActionStyleDefault handler:^(id z){[[SAAPIStore shared]toggleFavorite:a];[self reload];}]],[x addAction:[UIAlertAction actionWithTitle:@"复制预览" style:UIAlertActionStyleDefault handler:^(id z){UIPasteboard.generalPasteboard.string=[[SAAPIStore shared]previewForAPI:a phone:nil];}]],[x addAction:[UIAlertAction actionWithTitle:@"关闭" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:x animated:YES completion:nil];}
@end
