#import "SARootListController.h"
#import "SAConsoleController.h"
#import "SAAPIListController.h"
#import "SAAPIStore.h"
#import <Preferences/PSSpecifier.h>
@implementation SARootListController
- (NSArray *)specifiers { if(!_specifiers){ NSDictionary*s=[SAAPIStore shared].statistics; NSMutableArray*a=[NSMutableArray array];
 PSSpecifier*g=[PSSpecifier preferenceSpecifierNamed:@"API 工具" target:nil set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[g setProperty:[NSString stringWithFormat:@"已加载 %@ 个接口模板。",s[@"total"]] forKey:@"footerText"];[a addObject:g];[a addObject:[self button:@"打开接口控制台" action:@selector(showConsole) icon:@"rectangle.and.text.magnifyingglass" color:UIColor.systemBlueColor]];
 PSSpecifier*b=[PSSpecifier preferenceSpecifierNamed:@"接口浏览" target:nil set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[b setProperty:@"支持搜索、分类、收藏和单项参数预览。" forKey:@"footerText"];[a addObject:b];[a addObject:[self button:[NSString stringWithFormat:@"全部接口（%@）",s[@"total"]] action:@selector(showAll) icon:@"list.bullet" color:nil]];[a addObject:[self button:[NSString stringWithFormat:@"POST 接口（%@）",s[@"post"]] action:@selector(showPost) icon:@"arrow.up.circle" color:nil]];[a addObject:[self button:[NSString stringWithFormat:@"GET 接口（%@）",s[@"get"]] action:@selector(showGet) icon:@"arrow.down.circle" color:nil]];[a addObject:[self button:[NSString stringWithFormat:@"收藏（%@）",s[@"favorites"]] action:@selector(showFavorites) icon:@"star" color:nil]];
 PSSpecifier*r=[PSSpecifier preferenceSpecifierNamed:@"分析与导出" target:nil set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[r setProperty:[NSString stringWithFormat:@"域名 %@ · 明文 HTTP %@ · 风险标记 %@",s[@"domains"],s[@"http"],s[@"risky"]] forKey:@"footerText"];[a addObject:r];[a addObject:[self button:@"查看统计报告" action:@selector(showReport) icon:@"chart.bar" color:nil]];[a addObject:[self button:@"复制审计报告" action:@selector(copyReport) icon:@"doc.on.doc" color:nil]];_specifiers=[a copy]; } return _specifiers; }
- (PSSpecifier *)button:(NSString*)name action:(SEL)action icon:(NSString*)icon color:(UIColor*)color { PSSpecifier*p=[PSSpecifier preferenceSpecifierNamed:name target:self set:nil get:nil detail:nil cell:PSButtonCell edit:nil];p->action=action;if(@available(iOS 13,*)){UIImage*i=[UIImage systemImageNamed:icon];if(color)i=[i imageWithTintColor:color renderingMode:UIImageRenderingModeAlwaysOriginal];[p setProperty:i forKey:@"iconImage"];}return p; }
- (void)showConsole { [self.navigationController pushViewController:[SAConsoleController new] animated:YES]; }
- (void)open:(NSString*)method favorite:(BOOL)favorite { SAAPIListController*x=[SAAPIListController new];x.methodFilter=method;x.favoritesOnly=favorite;[self.navigationController pushViewController:x animated:YES]; }
- (void)showAll{[self open:nil favorite:NO];}- (void)showPost{[self open:@"POST" favorite:NO];}- (void)showGet{[self open:@"GET" favorite:NO];}- (void)showFavorites{[self open:nil favorite:YES];}
- (void)alert:(NSString*)title message:(NSString*)message { UIAlertController*a=[UIAlertController alertControllerWithTitle:title message:message preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"完成" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil]; }
- (void)showReport{[self alert:@"统计报告" message:[SAAPIStore shared].exportReport];}- (void)copyReport{UIPasteboard.generalPasteboard.string=[SAAPIStore shared].exportReport;[self alert:@"已复制" message:@"审计报告已复制到剪贴板。"];}
@end
