#import "SARootListController.h"
#import "SAAPIListController.h"
#import "SAAPIStore.h"
#import <Preferences/PSSpecifier.h>
@implementation SARootListController
- (NSArray *)specifiers{if(!_specifiers){NSDictionary*s=[[SAAPIStore shared]statistics];NSMutableArray*a=[NSMutableArray array];PSSpecifier*g=[PSSpecifier preferenceSpecifierNamed:@"🛡️ API 接口审计" target:self set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[g setProperty:[NSString stringWithFormat:@"从 Mach-O 内嵌数据恢复 %@ 个接口。仅提供本地浏览、风险扫描和请求预览。",s[@"total"]] forKey:@"footerText"];[a addObject:g];[a addObject:[self link:[NSString stringWithFormat:@"全部接口（%@）",s[@"total"]] sel:@selector(showAll) icon:@"list.bullet"]];[a addObject:[self link:[NSString stringWithFormat:@"POST 接口（%@）",s[@"post"]] sel:@selector(showPost) icon:@"arrow.up.circle"]];[a addObject:[self link:[NSString stringWithFormat:@"GET 接口（%@）",s[@"get"]] sel:@selector(showGet) icon:@"arrow.down.circle"]];[a addObject:[self link:[NSString stringWithFormat:@"收藏（%@）",s[@"favorites"]] sel:@selector(showFavorites) icon:@"star"]];PSSpecifier*r=[PSSpecifier preferenceSpecifierNamed:@"风险分析" target:nil set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[r setProperty:[NSString stringWithFormat:@"域名 %@ · 明文 HTTP %@ · 含风险标记 %@",s[@"domains"],s[@"http"],s[@"risky"]] forKey:@"footerText"];[a addObject:r];[a addObject:[self link:@"查看统计报告" sel:@selector(showReport) icon:@"chart.bar"]];[a addObject:[self link:@"复制审计报告" sel:@selector(copyReport) icon:@"doc.on.doc"]];[a addObject:[self link:@"复制 api.json 路径" sel:@selector(copyPath) icon:@"folder"]];PSSpecifier*d=[PSSpecifier preferenceSpecifierNamed:@"数据说明" target:nil set:nil get:nil detail:nil cell:PSGroupCell edit:nil];[d setProperty:@"支持 URL/域名搜索、GET/POST 分类、收藏、明文 HTTP/Token/签名/异常模板扫描以及手机号占位后的本地请求预览。面板不会发起接口请求。" forKey:@"footerText"];[a addObject:d];_specifiers=[a copy];}return _specifiers;}
- (PSSpecifier*)link:(NSString*)n sel:(SEL)s icon:(NSString*)i{PSSpecifier*p=[PSSpecifier preferenceSpecifierNamed:n target:self set:nil get:nil detail:nil cell:PSButtonCell edit:nil];p->action=s;if(@available(iOS 13,*))[p setProperty:[UIImage systemImageNamed:i] forKey:@"iconImage"];return p;}
- (void)open:(NSString*)m fav:(BOOL)f{SAAPIListController*x=[SAAPIListController new];x.methodFilter=m;x.favoritesOnly=f;[self.navigationController pushViewController:x animated:YES];}
- (void)showAll{[self open:nil fav:NO];}- (void)showPost{[self open:@"POST" fav:NO];}- (void)showGet{[self open:@"GET" fav:NO];}- (void)showFavorites{[self open:nil fav:YES];}
- (void)alert:(NSString*)t message:(NSString*)m{UIAlertController*a=[UIAlertController alertControllerWithTitle:t message:m preferredStyle:UIAlertControllerStyleAlert];[a addAction:[UIAlertAction actionWithTitle:@"完成" style:UIAlertActionStyleCancel handler:nil]];[self presentViewController:a animated:YES completion:nil];}
- (void)showReport{[self alert:@"审计统计" message:[[SAAPIStore shared]exportReport]];}
- (void)copyReport{UIPasteboard.generalPasteboard.string=[[SAAPIStore shared]exportReport];[self alert:@"已复制" message:@"审计报告已复制到剪贴板。"];}
- (void)copyPath{NSBundle*b=[NSBundle bundleForClass:self.class];UIPasteboard.generalPasteboard.string=[b pathForResource:@"api" ofType:@"json"];[self alert:@"已复制" message:@"内置 api.json 路径已复制。"];}@end
