#import <Preferences/PSListController.h>
#import <Preferences/PSSpecifier.h>
#import <Preferences/PSTableCell.h>
#import "../SCPaths.h"
#import <UIKit/UIKit.h>

static NSString *const SCChoiceKey=@"SCChoiceKey",*const SCChoiceTitles=@"SCChoiceTitles",*const SCChoiceValues=@"SCChoiceValues",*const SCChoiceDefault=@"SCChoiceDefault";
@interface SCRootListController : PSListController @end
static void SCStateChanged(CFNotificationCenterRef c,void *o,CFStringRef n,const void *obj,CFDictionaryRef u){SCRootListController *vc=(__bridge id)o;dispatch_async(dispatch_get_main_queue(),^{[vc reloadSpecifierID:@"ButtonHookStatus"];[vc reloadSpecifierID:@"LastActionDate"];[vc reloadSpecifierID:@"LastActionStatus"];});}
@implementation SCRootListController
- (instancetype)init{if((self=[super init])){CFNotificationCenterRef dc=CFNotificationCenterGetDarwinNotifyCenter();CFNotificationCenterAddObserver(dc,(__bridge const void*)self,SCStateChanged,CFSTR("com.spark.SneakyCam.actionstatechanged"),NULL,CFNotificationSuspensionBehaviorDeliverImmediately);CFNotificationCenterAddObserver(dc,(__bridge const void*)self,SCStateChanged,CFSTR("com.spark.SneakyCam.recordingstatechanged"),NULL,CFNotificationSuspensionBehaviorDeliverImmediately);}return self;}
- (BOOL)isChoicePage{return [[self.specifier propertyForKey:SCChoiceKey] length]>0;}
- (PSSpecifier *)item:(NSString *)name key:(NSString *)key def:(id)def cell:(PSCellType)cell{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:@selector(setPreferenceValue:specifier:) get:@selector(readPreferenceValue:) detail:Nil cell:cell edit:Nil];[s setProperty:key forKey:@"key"];[s setProperty:key forKey:@"id"];[s setProperty:def forKey:@"default"];return s;}
- (PSSpecifier *)choice:(NSString *)name key:(NSString *)key def:(id)def titles:(NSArray *)titles values:(NSArray *)values{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:SCRootListController.class cell:PSLinkCell edit:Nil];[s setProperty:key forKey:SCChoiceKey];[s setProperty:titles forKey:SCChoiceTitles];[s setProperty:values forKey:SCChoiceValues];[s setProperty:def forKey:SCChoiceDefault];id current=SCReadPreferences()[key]?:def;NSUInteger idx=[values indexOfObject:current];[s setProperty:(idx!=NSNotFound&&idx<titles.count)?titles[idx]:@"请选择" forKey:@"value"];return s;}
- (PSSpecifier *)button:(NSString *)name action:(SEL)action{PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:name target:self set:NULL get:NULL detail:Nil cell:PSButtonCell edit:Nil];s.buttonAction=action;return s;}
- (NSMutableArray *)choiceItems{NSString *key=[self.specifier propertyForKey:SCChoiceKey];NSArray *titles=[self.specifier propertyForKey:SCChoiceTitles]?:@[],*values=[self.specifier propertyForKey:SCChoiceValues]?:@[];NSMutableArray *a=[NSMutableArray arrayWithObject:[PSSpecifier groupSpecifierWithName:self.title?:@"选择"]];for(NSUInteger i=0;i<MIN(titles.count,values.count);i++){PSSpecifier *s=[PSSpecifier preferenceSpecifierNamed:titles[i] target:self set:NULL get:NULL detail:Nil cell:PSListItemCell edit:Nil];[s setProperty:key forKey:@"key"];[s setProperty:values[i] forKey:@"value"];[s setProperty:[NSString stringWithFormat:@"choice-%lu",(unsigned long)i] forKey:@"id"];[a addObject:s];}return a;}
- (NSArray *)specifiers{if(_specifiers)return _specifiers;if([self isChoicePage]){_specifiers=[self choiceItems];return _specifiers;}NSMutableArray *a=[NSMutableArray array];PSSpecifier *main=[PSSpecifier groupSpecifierWithName:@"SneakyCam 隐私相机"];[main setProperty:@"iOS 15–17 · Dopamine Rootless / RootHide" forKey:@"footerText"];[a addObject:main];[a addObject:[self item:@"功能总开关" key:@"Enabled" def:@NO cell:PSSwitchCell]];[a addObject:[self item:@"允许拍照片" key:@"PhotoEnabled" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"拍照静音" key:@"PhotoSilent" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"允许拍视频" key:@"VideoEnabled" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"允许录音" key:@"AudioEnabled" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"录像绿色指示点" key:@"RecordingIndicator" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"锁屏保持录制" key:@"LockScreenKeepRecording" def:@YES cell:PSSwitchCell]];[a addObject:[self item:@"保存到 /var/mobile/Media/Camera" key:@"SaveToRoot" def:@NO cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"前后双摄"]];[a addObject:[self item:@"系统相机内启用前后双摄" key:@"DualCamEnabled" def:@YES cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"相机"]];[a addObject:[self choice:@"选择摄像头" key:@"CameraDevice" def:@"AVCaptureDevicePositionBack" titles:@[@"后置摄像头",@"前置摄像头"] values:@[@"AVCaptureDevicePositionBack",@"AVCaptureDevicePositionFront"]]];[a addObject:[self choice:@"视频质量" key:@"VideoQuality" def:@"AVCaptureSessionPreset1920x1080" titles:@[@"288p",@"720p",@"1080p",@"2160p"] values:@[@"AVCaptureSessionPreset352x288",@"AVCaptureSessionPreset1280x720",@"AVCaptureSessionPreset1920x1080",@"AVCaptureSessionPreset3840x2160"]]];[a addObject:[self choice:@"视频帧率" key:@"FrameRate" def:@"60" titles:@[@"30 帧",@"60 帧",@"120 帧（非 4K）",@"240 帧（非 4K）"] values:@[@"30",@"60",@"120",@"240"]]];[a addObject:[self item:@"播放音视频时禁用" key:@"DisableIfPlayback" def:@NO cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"音量键"]];[a addObject:[self item:@"使用音量键" key:@"UseVolumeButtons" def:@YES cell:PSSwitchCell]];[a addObject:[self choice:@"音量减动作" key:@"VolumeDownAction" def:@"photo" titles:@[@"拍照",@"录像",@"录音",@"关闭"] values:@[@"photo",@"video",@"audio",@"off"]]];[a addObject:[self choice:@"音量加动作" key:@"VolumeUpAction" def:@"video" titles:@[@"拍照",@"录像",@"录音",@"关闭"] values:@[@"photo",@"video",@"audio",@"off"]]];[a addObject:[self item:@"震动反馈" key:@"HapticFeedback" def:@YES cell:PSSwitchCell]];
[a addObject:[PSSpecifier groupSpecifierWithName:@"最近操作"]];[a addObject:[self item:@"按键兼容状态" key:@"ButtonHookStatus" def:@"等待 SpringBoard 加载" cell:PSTitleValueCell]];[a addObject:[self item:@"时间" key:@"LastActionDate" def:@"尚无操作" cell:PSTitleValueCell]];[a addObject:[self item:@"状态" key:@"LastActionStatus" def:@"等待按键或控制中心操作" cell:PSTitleValueCell]];[a addObject:[self button:@"打开 Camera 文件夹" action:@selector(openCamera)]];PSSpecifier *footer=[PSSpecifier emptyGroupSpecifier];[footer setProperty:@"双击音量加/减可分别设置拍照、录像、录音或关闭。\n@Huayuarc Fix" forKey:@"footerText"];[a addObject:footer];_specifiers=a;return _specifiers;}
- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath{if(![self isChoicePage])return;PSSpecifier *s=[self specifierAtIndexPath:indexPath];id current=SCReadPreferences()[[self.specifier propertyForKey:SCChoiceKey]]?:[self.specifier propertyForKey:SCChoiceDefault];if([cell respondsToSelector:@selector(setChecked:)])[(PSTableCell*)cell setChecked:[[s propertyForKey:@"value"] isEqual:current]];}
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{if(![self isChoicePage]){[super tableView:tableView didSelectRowAtIndexPath:indexPath];return;}PSSpecifier *s=[self specifierAtIndexPath:indexPath];id value=[s propertyForKey:@"value"];NSString *key=[self.specifier propertyForKey:SCChoiceKey];if(key&&value){SCWritePreference(key,value);CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),CFSTR("com.spark.SneakyCam"),NULL,NULL,YES);}[tableView reloadData];[self.navigationController popViewControllerAnimated:YES];}
- (id)readPreferenceValue:(PSSpecifier *)s{return SCReadPreferences()[s.properties[@"key"]]?:s.properties[@"default"];}
- (void)setPreferenceValue:(id)v specifier:(PSSpecifier *)s{NSString *key=s.properties[@"key"];SCWritePreference(key,v);CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),CFSTR("com.spark.SneakyCam"),NULL,NULL,YES);if([key isEqualToString:@"Enabled"]||[key isEqualToString:@"RecordingIndicator"])CFNotificationCenterPostNotification(CFNotificationCenterGetDarwinNotifyCenter(),CFSTR("com.spark.SneakyCam.enabledchanged"),NULL,NULL,YES);}
- (void)openCamera{NSString *dir=@"/var/mobile/Media/Camera",*anchor=[dir stringByAppendingPathComponent:@".SneakyCam-OpenHere"];NSFileManager *fm=NSFileManager.defaultManager;[fm createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:nil];if(![fm fileExistsAtPath:anchor])[@"SneakyCam folder anchor" writeToFile:anchor atomically:YES encoding:NSUTF8StringEncoding error:nil];NSURL *url=[NSURL URLWithString:@"filza://view/var/mobile/Media/Camera/.SneakyCam-OpenHere"];if([UIApplication.sharedApplication canOpenURL:url])[UIApplication.sharedApplication openURL:url options:@{} completionHandler:nil];else{SCWritePreference(@"LastActionStatus",@"未检测到 Filza，请安装后重试");[self reloadSpecifierID:@"LastActionStatus"];}}
- (void)dealloc{CFNotificationCenterRemoveObserver(CFNotificationCenterGetDarwinNotifyCenter(),(__bridge const void*)self,NULL,NULL);}
@end
