#import <Foundation/Foundation.h>
#import <substrate.h>
#import <notify.h>
#import <limits.h>
#import <stdint.h>
#import <string.h>
#import <objc/message.h>
#import <objc/runtime.h>
#import <CPUthermalPaths.h>
#import "Shared/CPUthermalSwiftBridge.h"
#import <IOKit/IOKitLib.h>
#import <os/lock.h>
