#import <Preferences/PSListController.h>
#import <Preferences/PSSpecifier.h>
#import <UIKit/UIKit.h>
#import <objc/message.h>
#import <CPUthermalPaths.h>

@interface CPUthermalRefreshExcludeController : PSListController <UISearchResultsUpdating>
@property(nonatomic,strong) NSArray<NSDictionary *> *allApps;
@property(nonatomic,copy) NSString *searchTerm;
@property(nonatomic,strong) UISearchController *searchController;
@end
@implementation CPUthermalRefreshExcludeController
- (void)viewDidLoad { [super viewDidLoad]; self.navigationItem.title=S("不注入刷新率"); self.searchController=[[UISearchController alloc]initWithSearchResultsController:nil];self.searchController.searchResultsUpdater=self;self.searchController.obscuresBackgroundDuringPresentation=NO;self.searchController.searchBar.placeholder=S("名称或 Bundle ID");self.navigationItem.searchController=self.searchController;self.navigationItem.hidesSearchBarWhenScrolling=NO;self.definesPresentationContext=YES; }
- (NSString *)stringFromObject:(id)o selectors:(NSArray *)names { for(NSString*n in names){SEL sel=NSSelectorFromString(n);if(![o respondsToSelector:sel])continue;id v=((id(*)(id,SEL))objc_msgSend)(o,sel);if([v isKindOfClass:[NSString class]]&&[v length])return v;}return nil; }
- (void)addApp:(NSString *)path map:(NSMutableDictionary *)map { NSDictionary*i=[NSDictionary dictionaryWithContentsOfFile:[path stringByAppendingPathComponent:S("Info.plist")]];NSString*bid=i[S("CFBundleIdentifier")];if(![bid isKindOfClass:[NSString class]]||!bid.length||[bid hasPrefix:S("com.apple.")])return;NSString*n=i[S("CFBundleDisplayName")];if(![n isKindOfClass:[NSString class]]||!n.length)n=i[S("CFBundleName")];if(![n isKindOfClass:[NSString class]]||!n.length)n=bid;map[bid]=@{S("id"):bid,S("name"):n}; }
- (NSArray *)enumerateApps { NSMutableDictionary*map=[NSMutableDictionary dictionary];@try{Class c=NSClassFromString(S("LSApplicationWorkspace"));id w=[c respondsToSelector:NSSelectorFromString(S("defaultWorkspace"))]?((id(*)(id,SEL))objc_msgSend)(c,NSSelectorFromString(S("defaultWorkspace"))):nil;id apps=[w respondsToSelector:NSSelectorFromString(S("allApplications"))]?((id(*)(id,SEL))objc_msgSend)(w,NSSelectorFromString(S("allApplications"))):nil;if([apps isKindOfClass:[NSArray class]])for(id proxy in apps){NSString*bid=[self stringFromObject:proxy selectors:@[S("applicationIdentifier"),S("bundleIdentifier")]];if(!bid.length||[bid hasPrefix:S("com.apple.")])continue;NSString*n=[self stringFromObject:proxy selectors:@[S("localizedName"),S("itemName"),S("localizedShortName")]]?:bid;map[bid]=@{S("id"):bid,S("name"):n};}}@catch(__unused NSException*e){}NSFileManager*fm=NSFileManager.defaultManager;for(NSString*root in @[S("/var/mobile/Containers/Bundle/Application"),S("/var/containers/Bundle/Application")])for(NSString*uuid in [fm contentsOfDirectoryAtPath:root error:nil]?:@[])for(NSString*entry in [fm contentsOfDirectoryAtPath:[root stringByAppendingPathComponent:uuid] error:nil]?:@[])if([[entry pathExtension]caseInsensitiveCompare:S("app")]==NSOrderedSame)[self addApp:[[root stringByAppendingPathComponent:uuid]stringByAppendingPathComponent:entry] map:map];return map.allValues; }
- (NSMutableSet *)excluded { id v=CPUthermalReadPrefs()[S("refreshRateExcludedApps")];return [NSMutableSet setWithArray:[v isKindOfClass:[NSArray class]]?v:@[]]; }
- (NSArray *)visible { if(!self.allApps)self.allApps=[self enumerateApps];NSString*t=[[self.searchTerm?:S("") stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]lowercaseString];NSMutableArray*a=[NSMutableArray array];for(NSDictionary*x in self.allApps)if(!t.length||[[x[S("name")]lowercaseString]containsString:t]||[[x[S("id")]lowercaseString]containsString:t])[a addObject:x];NSSet*e=[self excluded];[a sortUsingComparator:^NSComparisonResult(NSDictionary*x,NSDictionary*y){BOOL xe=[e containsObject:x[S("id")]],ye=[e containsObject:y[S("id")]];if(xe!=ye)return xe?NSOrderedAscending:NSOrderedDescending;NSComparisonResult r=[x[S("name")]localizedCaseInsensitiveCompare:y[S("name")]];return r==NSOrderedSame?[x[S("id")]compare:y[S("id")]]:r;}];return a; }
- (void)rebuild { if(!_specifiers)_specifiers=[NSMutableArray array];[_specifiers removeAllObjects];@try{NSArray*apps=[self visible];NSUInteger count=[self excluded].count;PSSpecifier*g=[PSSpecifier emptyGroupSpecifier];NSString*f=self.searchTerm.length?[NSString stringWithFormat:S("找到 %lu 个应用；已排除应用优先显示。"),(unsigned long)apps.count]:[NSString stringWithFormat:S("已排除 %lu 个应用。开关开启表示该应用不注入刷新率模块，恢复应用原生刷新率。"),(unsigned long)count];if(!self.allApps.count)f=S("没有枚举到第三方应用。");[g setProperty:f forKey:S("footerText")];[_specifiers addObject:g];for(NSDictionary*x in apps){PSSpecifier*sp=[PSSpecifier preferenceSpecifierNamed:x[S("name")] target:self set:@selector(setExcluded:specifier:) get:@selector(isExcluded:) detail:nil cell:PSSwitchCell edit:nil];sp.identifier=x[S("id")];[sp setProperty:x[S("id")] forKey:S("id")];[sp setProperty:x[S("id")] forKey:S("PSIDKey")];[_specifiers addObject:sp];}}@catch(__unused NSException*e){[_specifiers removeAllObjects];PSSpecifier*g=[PSSpecifier emptyGroupSpecifier];[g setProperty:S("应用列表加载异常。") forKey:S("footerText")];[_specifiers addObject:g];} }
- (NSArray *)specifiers { if(!_specifiers)[self rebuild];return _specifiers; }
- (id)isExcluded:(PSSpecifier *)sp { return @([[self excluded]containsObject:sp.identifier?:[sp propertyForKey:S("id")]]); }
- (void)setExcluded:(id)value specifier:(PSSpecifier *)sp { NSString*bid=sp.identifier?:[sp propertyForKey:S("id")];if(!bid.length)return;NSMutableSet*e=[self excluded];[value boolValue]?[e addObject:bid]:[e removeObject:bid];NSMutableDictionary*p=CPUthermalReadMutablePrefs()?:[NSMutableDictionary dictionary];p[S("refreshRateExcludedApps")]=[[e allObjects]sortedArrayUsingSelector:@selector(compare:)];CPUthermalWritePrefs(p);CPUthermalPostRefreshExclusion(bid,[value boolValue]);dispatch_async(dispatch_get_main_queue(),^{[self rebuild];[self.table reloadData];}); }
- (void)updateSearchResultsForSearchController:(UISearchController *)c { self.searchTerm=c.searchBar.text?:S("");[self rebuild];[self.table reloadData]; }
@end
