include $(THEOS)/makefiles/common.mk

TWEAK_NAME = RootHideSupport
RootHideSupport_FILES = Tweak.m
RootHideSupport_CFLAGS = -fobjc-arc -Wno-deprecated-declarations
RootHideSupport_FRAMEWORKS = Foundation UIKit

include $(THEOS_MAKE_PATH)/tweak.mk
