#import "PMPaths.h"

static NSString * const PMBase=@"/var/mobile/Containers/Shared/AppGroup";
static NSString * const PMDataSuffix=@"var/mobile/Library/PictureModule";
static NSString * const PMPrefsSuffix=@"var/mobile/Library/Preferences";
static NSString * const PMBundleSuffix=@"Library/ControlCenter/Bundles/PictureModule1.bundle";

static NSArray *PMJBRoots(void){NSMutableArray *a=[NSMutableArray array];for(NSString *n in [[NSFileManager defaultManager]contentsOfDirectoryAtPath:PMBase error:nil]?:@[]){if([n hasPrefix:@".jbroot-"])[a addObject:[PMBase stringByAppendingPathComponent:n]];}return a;}
static NSTimeInterval PMMTime(NSString *p){NSDate *date=[[[NSFileManager defaultManager]attributesOfItemAtPath:p error:nil]fileModificationDate];return (date?:[NSDate distantPast]).timeIntervalSince1970;}
static NSString *PMCurrentRoot(void){NSString *best=nil;NSInteger score=-1;NSTimeInterval mt=0;for(NSString *r in PMJBRoots()){NSInteger s=0;if([[NSFileManager defaultManager]fileExistsAtPath:[r stringByAppendingPathComponent:PMBundleSuffix]])s+=100;if([[NSFileManager defaultManager]fileExistsAtPath:[r stringByAppendingPathComponent:@"Library/ControlCenter/Bundles"]])s+=20;if([[NSFileManager defaultManager]fileExistsAtPath:[r stringByAppendingPathComponent:@"Library/MobileSubstrate"]])s+=10;if([[NSFileManager defaultManager]fileExistsAtPath:[r stringByAppendingPathComponent:@"usr/lib"]])s+=5;NSTimeInterval t=PMMTime(r);if(s>score||(s==score&&t>mt)){best=r;score=s;mt=t;}}return best;}
static void PMEnsure(NSString *p){[[NSFileManager defaultManager]createDirectoryAtPath:p withIntermediateDirectories:YES attributes:@{NSFilePosixPermissions:@0775} error:nil];}
static void PMCopyNewest(NSArray *sources,NSString *dst){NSFileManager *fm=[NSFileManager defaultManager];NSMutableDictionary *latest=[NSMutableDictionary dictionary];for(NSString *s in sources){BOOL dir=NO;if(![fm fileExistsAtPath:s isDirectory:&dir]||!dir)continue;for(NSString *n in [fm contentsOfDirectoryAtPath:s error:nil]?:@[]){NSString *p=[s stringByAppendingPathComponent:n];BOOL d=NO;if([fm fileExistsAtPath:p isDirectory:&d]&&d)continue;NSString *old=latest[n];if(!old||PMMTime(p)>PMMTime(old))latest[n]=p;}}for(NSString *n in latest){NSString *to=[dst stringByAppendingPathComponent:n];NSString *from=latest[n];if(![fm fileExistsAtPath:to]||PMMTime(from)>PMMTime(to)){[fm removeItemAtPath:to error:nil];[fm copyItemAtPath:from toPath:to error:nil];}}}
NSString *PMDataRoot(void){NSString *r=PMCurrentRoot();if(r){NSString *p=[r stringByAppendingPathComponent:PMDataSuffix];PMEnsure(p);return p;}NSString *p=[[NSFileManager defaultManager]fileExistsAtPath:@"/var/jb"]?@"/var/jb/var/mobile/Library/PictureModule":@"/var/mobile/Library/PictureModule";PMEnsure(p);return p;}
NSString *PMPrefsPath(NSString *domain){NSString *r=PMCurrentRoot();NSString *dir=r?[r stringByAppendingPathComponent:PMPrefsSuffix]:([[NSFileManager defaultManager]fileExistsAtPath:@"/var/jb"]?@"/var/jb/var/mobile/Library/Preferences":@"/var/mobile/Library/Preferences");PMEnsure(dir);return [dir stringByAppendingPathComponent:[domain stringByAppendingString:@".plist"]];}
NSDictionary *PMReadDomain(NSString *domain){NSDictionary *d=[NSDictionary dictionaryWithContentsOfFile:PMPrefsPath(domain)];return [d isKindOfClass:NSDictionary.class]?d:@{};}
BOOL PMWriteDomainValue(NSString *domain,NSString *key,id value){NSString *p=PMPrefsPath(domain);NSMutableDictionary *d=[NSMutableDictionary dictionaryWithDictionary:[NSDictionary dictionaryWithContentsOfFile:p]?:@{}];if(value)d[key]=value;else[d removeObjectForKey:key];return [d writeToFile:p atomically:YES];}
void PMPrepareAndMigrate(void){static dispatch_once_t once;dispatch_once(&once,^{NSString *current=PMCurrentRoot();if(!current)return;NSFileManager *fm=[NSFileManager defaultManager];NSString *data=[current stringByAppendingPathComponent:PMDataSuffix];PMEnsure(data);NSMutableArray *dataSources=[NSMutableArray arrayWithObjects:@"/var/mobile/Library/PictureModule",@"/var/jb/var/mobile/Library/PictureModule",nil];for(NSString *r in PMJBRoots())if(![r isEqual:current])[dataSources addObject:[r stringByAppendingPathComponent:PMDataSuffix]];PMCopyNewest(dataSources,data);NSString *prefs=[current stringByAppendingPathComponent:PMPrefsSuffix];PMEnsure(prefs);NSArray *domains=@[@"com.4nni3.picturemodule_1",@"com.4nni3.picturemodule_2",@"com.4nni3.picturemodule_3",@"com.4nni3.picturemodule_4",@"com.4nni3.picturemodule_5",@"com.huayuarc.picturemodule16.1",@"com.huayuarc.picturemodule16.2",@"com.huayuarc.picturemodule16.3",@"com.huayuarc.picturemodule16.4",@"com.huayuarc.picturemodule16.5"];for(NSString *domain in domains){NSMutableArray *c=[NSMutableArray arrayWithObjects:[@"/var/mobile/Library/Preferences" stringByAppendingPathComponent:[domain stringByAppendingString:@".plist"]],[@"/var/jb/var/mobile/Library/Preferences" stringByAppendingPathComponent:[domain stringByAppendingString:@".plist"]],nil];for(NSString *r in PMJBRoots())if(![r isEqual:current])[c addObject:[[r stringByAppendingPathComponent:PMPrefsSuffix]stringByAppendingPathComponent:[domain stringByAppendingString:@".plist"]]];NSString *dst=[prefs stringByAppendingPathComponent:[domain stringByAppendingString:@".plist"]];NSString *newest=nil;for(NSString *x in c)if([fm fileExistsAtPath:x]&&(!newest||PMMTime(x)>PMMTime(newest)))newest=x;if(newest&&(![fm fileExistsAtPath:dst]||PMMTime(newest)>PMMTime(dst))){[fm removeItemAtPath:dst error:nil];[fm copyItemAtPath:newest toPath:dst error:nil];}for(NSString *x in c)[fm removeItemAtPath:x error:nil];}for(NSString *s in dataSources)if(![s isEqual:data])[fm removeItemAtPath:s error:nil];});}
